Fix coverage of unit tests (#2178)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -253,24 +253,17 @@ jobs:
                   exit 0
               fi
               cd content
-              echo "installing venv"
-              NO_HOOKS=1 SETUP_PY2=yes .hooks/bootstrap >> /tmp/lint_env_installation.log
-              echo "finished script installation"
-              source ./venv/bin/activate
-              pip3 install -r .circleci/build-requirements.txt >> /tmp/lint_env_installation.log
+              echo "lint files changed. running lint"
               
-              # installing local sdk inside venv
-              
-              # uninstall demisto-sdk that installed from content (could be dependency conflict between them)
-              pip3 uninstall -y demisto-sdk
-              pip3 install ~/project >> /tmp/lint_env_installation.log
-              demisto-sdk -v
-              echo ""
-              echo "lint files changed running lint"
               # python file (CommonServerPython lint is running over python 3 and 2)
-              # we use `demisto-sdk` because we're inside content local env and not on poetry local env
-              demisto-sdk lint -i ./Packs/Base/Scripts/CommonServerPython
-              
+              demisto-sdk lint -i ./Packs/Base/Scripts/CommonServerPython --coverage-report ~/project/coverage-report
+              if [[ -f ~/project/coverage-report/html/index.html && -f ~/project/coverage-report/coverage.xml ]]
+                then
+                  echo "coverage files found."
+                else
+                  echo "coverage files not found."
+                  exit 1
+              fi
               # ps file
               demisto-sdk lint -i ./Packs/Base/Scripts/CommonServerPowerShell
               
